spring.application.name=gramavoice-backend
server.port=${PORT:${SERVER_PORT:8085}}

spring.datasource.url=${GRAMAVOICE_DB_URL:jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.username=${GRAMAVOICE_DB_USERNAME:postgres.nffwpckgcrwaljmpxcef}
spring.datasource.password=${GRAMAVOICE_DB_PASSWORD:Prajubhai143}
spring.datasource.driver-class-name=${GRAMAVOICE_DB_DRIVER:org.postgresql.Driver}
spring.jpa.database-platform=${GRAMAVOICE_JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

spring.h2.console.enabled=false
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jackson.time-zone=Asia/Kolkata
spring.jackson.serialization.write-dates-as-timestamps=false

sarvam.enabled=${SARVAM_ENABLED:true}
sarvam.api-key=${SARVAM_API_KEY:}
sarvam.base-url=${SARVAM_BASE_URL:https://api.sarvam.ai}
sarvam.model=${SARVAM_MODEL:sarvam-30b}

app.auth.secret=${APP_AUTH_SECRET:change-this-secret-before-deploy}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB
