name: Unit.yml

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  test-job:
    name: "Unit Tests — API (300)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Report File
        run: |
          if [ -f "tests/reports/Unit_Test_Report.xlsx" ]; then
            echo "Successfully found tests/reports/Unit_Test_Report.xlsx"
          else
            echo "Error: tests/reports/Unit_Test_Report.xlsx missing!" && exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unit-Test-Report
          path: tests/reports/Unit_Test_Report.xlsx
